from prolothar_common.models.eventlog.event import Event
from typing import Hashable

class Trace:
    events: list[Event]
    attributes: dict

    def __init__(self, trace_id: Hashable, events: list[Event], attributes: dict[str, object] = None): ...
    def get_id(self) -> Hashable: ...
    def get_first_index_of_first_matching_activity(self, activity_set: set) -> int: ...
    def get_last_index_of_first_matching_activity(self, activity_set: set) -> int: ...
    def contains_activity(self, activity: object) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_activity_list(self) -> list: ...